version: '3.8'

services:
  excalidraw-proxy:
    image: nginx:alpine
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        
        # HTTP Router
        - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.parlaymojo.com`)"
        - "traefik.http.routers.excalidraw.entrypoints=web"
        - "traefik.http.routers.excalidraw.middlewares=redirect-to-https"
        
        # HTTPS Router
        - "traefik.http.routers.excalidraw-secure.rule=Host(`excalidraw.parlaymojo.com`)"
        - "traefik.http.routers.excalidraw-secure.entrypoints=websecure"
        - "traefik.http.routers.excalidraw-secure.tls=true"
        - "traefik.http.routers.excalidraw-secure.tls.certresolver=letsencrypt"
        
        # Service
        - "traefik.http.services.excalidraw.loadbalancer.server.port=80"
        
        # Redirect middleware
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
        
    volumes:
      - ./deploy/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    
networks:
  traefik-public:
    external: true