name: Deploy to excalidraw.parlaymojo.com

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 92.118.56.108
        username: pascal
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          # Navigate to the app directory
          mkdir -p /home/pascal/www/excalidraw.parlaymojo.com
          cd /home/pascal/www/excalidraw.parlaymojo.com
          
          # Clone or pull latest changes
          if [ ! -d ".git" ]; then
            git clone https://github.com/PascalAI2024/excalidraw-team.git .
          else
            git pull origin main
          fi
          
          # Update environment variables
          cat > .env << 'EOF'
          VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
          DATABASE_URL="${{ secrets.DATABASE_URL }}"
          VITE_APP_BACKEND_URL=https://excalidraw.parlaymojo.com/api
          NODE_ENV=production
          EOF
          
          # Also create .env.local for backwards compatibility
          cp .env .env.local
          
          # Update server .env
          cat > server/.env << 'EOF'
          DATABASE_URL="${{ secrets.DATABASE_URL }}"
          FRONTEND_URL=https://excalidraw.parlaymojo.com
          PORT=3001
          EOF
          
          # Install dependencies
          npm install --legacy-peer-deps
          
          # Build the frontend
          npm run build
          
          # Install server dependencies
          cd server
          npm install
          
          # Run database migrations
          cd ..
          npx prisma generate
          npx prisma migrate deploy
          
          # Use local PM2 if global not available
          export PATH=$PATH:./node_modules/.bin
          
          # Restart services with PM2
          npx pm2 restart excalidraw-backend || npx pm2 start server/src/index.js --name excalidraw-backend
          npx pm2 restart excalidraw-frontend || npx pm2 serve build 5173 --name excalidraw-frontend --spa
          
          # Save PM2 configuration
          npx pm2 save
          
          # Note: nginx reload requires manual configuration